# Generated by Django 6.1.1 on 2026-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='prod-item', max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Enterprise SaaS', 'Enterprise SaaS'), ('AI & Automation', 'AI & Automation'), ('E-Commerce', 'E-Commerce'), ('Logistics', 'Logistics'), ('Cloud Infra', 'Cloud Infra')], default='Enterprise SaaS', max_length=64)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Beta', 'Beta'), ('In Incubation', 'In Incubation'), ('Enterprise Pilot', 'Enterprise Pilot')], default='Live', max_length=32)),
                ('mrr', models.CharField(default='$10,000', max_length=32)),
                ('active_users', models.CharField(default='10,000+', max_length=32)),
                ('uptime', models.CharField(default='99.99%', max_length=16)),
                ('features', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_latest_launch', models.BooleanField(default=False)),
                ('launch_date', models.CharField(default='2026-09-01', max_length=32)),
                ('demo_url', models.URLField(blank=True, max_length=256)),
                ('accent_color', models.CharField(default='#F05A28', max_length=16)),
                ('architecture_tier', models.CharField(default='Tier-1 Distributed Core', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-is_latest_launch', '-created_at'],
            },
        ),
    ]
