# Generated by Django 6.1.1 on 2026-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('processing', 'Processing'), ('dispatched', 'Dispatched / In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=32)),
                ('items', models.JSONField(blank=True, default=list)),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
