# Generated by Django 6.1.1 on 2026-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('tagline', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('capabilities', models.JSONField(default=list)),
                ('team_size', models.CharField(max_length=64)),
                ('flagship', models.CharField(max_length=128)),
                ('icon_name', models.CharField(default='Rocket', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('channel', models.CharField(choices=[('email', 'Email Desk'), ('whatsapp', 'WhatsApp Direct'), ('messenger', 'Messenger'), ('instagram', 'Instagram DM'), ('web', 'Web Terminal')], default='email', max_length=32)),
                ('subject', models.CharField(default='Enterprise SaaS Inquiry', max_length=256)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('replied', 'Replied')], default='unread', max_length=16)),
                ('replies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('node_type', models.CharField(default='Cloud Hub', max_length=64)),
                ('latency', models.IntegerField(default=20)),
                ('active_services', models.IntegerField(default=16)),
                ('coordinates', models.JSONField(default=dict)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('quote', models.TextField()),
                ('avatar_text', models.CharField(default='SK', max_length=8)),
                ('metric', models.CharField(max_length=64)),
                ('product_used', models.CharField(max_length=128)),
            ],
        ),
    ]
